fforum/config/routes.rb
Fforum::Application.routes.draw do
  resources :user_levels

  resources :boards do
    resources :board_threads, only: [:index, :new, :create]
    resources :user_board_permissions, only: [:index, :new, :create]
  end
  match '/boards/:id/marked/threads', to: 'boards#marked_threads', via: 'get',
    as: 'board_marked_threads'
  match '/boards/:id/marked/comments', to: 'boards#marked_comments', via: 'get',
    as: 'board_marked_comments'

  resources :board_threads, only: [:show, :edit, :update, :destroy] do
    resources :thread_comments, only: [:index, :new, :create]
  end
  match '/board_threads/:id/report', to: 'board_threads#report', via: 'get',
    as: 'report_board_thread'
  match '/board_threads/:id/mark', to: 'board_threads#mark', via: 'get',
    as: 'mark_board_thread'
  match '/board_threads/:id/add_review', to: 'board_threads#add_review', via: 'get',
    as: 'add_review_board_thread'

  resources :thread_comments, only: [:show, :edit, :update, :destroy]
  match 'thread_comments/:id/report', to: 'thread_comments#report', via: 'get',
    as: 'report_thread_comment'
  match 'thread_comments/:id/mark', to: 'thread_comments#mark', via: 'get',
    as: 'mark_thread_comment'
  match 'thread_comments/:id/add_review', to: 'thread_comments#add_review', via: 'get',
    as: 'add_review_thread_comment'
  
  resources :user_board_permissions, only: [:show, :edit, :update, :destroy]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via:'get'

  root to: 'boards#index'

  

end

fforum/app/models/board.rb
class Board < ActiveRecord::Base
  validates :title, presence: true
  validates :title, length: { in: 1..80 }
  has_many :board_threads, dependent: :destroy
  has_many :thread_comments, through: :board_threads
  belongs_to :user
  has_many :user_board_permissions

  self.per_page = 10
end

fforum/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy,
    :marked_threads, :marked_comments]

  # GET /boards
  # GET /boards.json
  def index
    if BoardPolicy.index?(current_user)
      if signed_in? && current_user.admin?
        @boards = Board.order("boards.title").paginate(page: params[:page])
      else
        @boards = Board.where(publicly_listed: true).
          order("LOWER(boards.title)").paginate(page: params[:page])
      end
    else
      redirect_to(root_path) 
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    redirect_to(root_path) unless BoardPolicy.show?(current_user, @board)
    @board_threads = BoardThread.includes("thread_comments").
      where(board_id: @board.id).order("thread_comments.created_at desc").
      paginate(page: params[:page])
  end

  # GET /boards/new
  def new
    if BoardPolicy.new?(current_user)
      @board = Board.new
    else
      redirect_to(root_path)
    end
  end

  # GET /boards/1/edit
  def edit
    redirect_to(root_path) unless BoardPolicy.edit?(current_user, @board)
  end

  # POST /boards
  # POST /boards.json
  def create
    if BoardPolicy.create?(current_user)
      @board = Board.new(board_params)
      @board.user_id = current_user.id
      
      respond_to do |format|
        if @board.save
          format.html { redirect_to @board, notice: 'Board was successfully created.' }
          format.json { render action: 'show', status: :created, location: @board }
        else
          format.html { render action: 'new' }
          format.json { render json: @board.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to(root_path)
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    if BoardPolicy.update?(current_user, @board)
      respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to(root_path)
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    if BoardPolicy.destroy?(current_user, @board)
      @board.destroy
      respond_to do |format|
        format.html { redirect_to boards_url }
        format.json { head :no_content }
      end
    else
      redirect_to(root_path)
    end
  end

  def marked_threads
    if BoardPolicy.marked_threads?(current_user, @board)
      @marked_threads = BoardThread.where.not(reported_number: nil).where.not(reported_number: 0).paginate(page: params[:page])
    else
      redirect_to board_path(@board)
    end
  end

  def marked_comments
    if BoardPolicy.marked_comments?(current_user, @board)
      @marked_comments = ThreadComment.where.not(reported_number: nil).where.not(reported_number: 0).paginate(page: params[:page])
    else
      redirect_to board_path(@board)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :description, :publicly_listed,
        :public_read, :public_thread_create, :public_thread_reply)
    end
end

fforum/app/helpers/boards_helper.rb
module BoardsHelper
  def board_page_path(board, page_number)
    board_path(board) + "/p#{page_number}"
  end
end

fforum/app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :publicly_listed %>
    <%= f.check_box :publicly_listed %>
  </div>
  <div class="field">
    <%= f.label :publicly_readable %>
    <%= f.check_box :public_read %>
  </div>
  <div class="field">
    <%= f.label :publicly_postable %>
    <%= f.check_box :public_thread_create %>
  </div>
  <div class="field">
    <%= f.label :publicly_commentable %>
    <%= f.check_box :public_thread_reply %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fforum/app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

fforum/app/views/boards/index.html.erb
<div class="well">
  <h1 class="text-center">Welcome to Blueit!</h1>
  <h3 class="text-center">Make your own message board!</h3>
</div>

<div class="row-fluid">
  <section class="span9">
    <%= will_paginate @boards %>
    <% @boards.each do |board| %>
      <article class="thread-box board-entry well">
        <ul class="inline">
          <li class="board-entry-title"><%= link_to board.title, board %></li>
          <% if signed_in? && current_user.admin? %>
              <li class="pull-right"><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <li class="pull-right"><%= link_to 'Edit', edit_board_path(board) %></li>
          <% end %>
        </ul>
      </article>
    <% end %>
    <%= will_paginate @boards %>
  </section>
  <section class="span3">
    <%= render "shared/site_info_panel" %>
    <%= render "shared/signin_panel" %>
    <%= render "shared/new_board_panel" %>
  </section>
</div>

fforum/app/views/boards/marked_comments.html.erb
<h1>Comments Marked for Review on "<%= @board.title %>"</h1>
<div class="row-fluid">
  <section class="span9">
    <% @marked_comments.each do |comment| %>
      <% thread = comment.board_thread %>
      <article class="marked-comment-info thread-box well">
        Thread Title: <%= link_to comment.board_thread.title, board_thread_path(thread) %> |
        Posted by: <%= comment.user.name %> -
        <% if thread.user.board_permission(comment.board_thread.board) %>
          <%= link_to "Edit Board Permissions?", user_board_permission_path(comment.board_thread.user.board_permission thread.board) %>
        <% else %>
          <%= link_to "Add Board Permissions?", new_board_user_board_permission_path(comment.board_thread.board) + "?user_id=#{comment.board_thread.user.id}" %>
        <% end %>

        <div class="sample-comment">
          <%= comment.content %>
        </div>

        <%= link_to "Edit Comment?", edit_thread_comment_path(comment) %>
      </article>
    <% end %>
  </section>
  <section class="nav side-bar span3">
    <%= render "shared/board_info_panel" %>
    <%= render "shared/administration_panel" %>
  </section>
</div>

fforum/app/views/boards/marked_threads.html.erb
<h1>Threads Marked for Review on "<%= @board.title %>"</h1>
<div class="row-fluid">
  <section class="span9">
    <% @marked_threads.each do |thread| %>
      <article class="marked-thread-info thread-box well">
        Title: <%= link_to thread.title, board_thread_path(thread) %> |
        Link: <%= link_to thread.link, thread.link %> |
        Posted by: <%= thread.user.name %> -
        <% if thread.user.board_permission(thread.board) %>
          <%= link_to "Edit Board Permissions?", user_board_permission_path(thread.user.board_permission thread.board) %>
        <% else %>
          <%= link_to "Add Board Permissions?", new_board_user_board_permission_path(thread.board) + "?user_id=#{thread.user.id}" %>
        <% end %> |
        <%= link_to "Edit Thread?", edit_board_thread_path(thread) %>
      </article>
    <% end %>
  </section>
  <section class="nav side-bar span3">
    <%= render "shared/board_info_panel" %>
    <%= render "shared/administration_panel" %>
  </section>
</div>

fforum/app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

fforum/app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>
<% threads = @board_threads %>
<div class="row-fluid">
  <section class="thread-list span9">
    <%= will_paginate @board_threads %>
    <% threads.each do |thread| %>
      <div class="thread-box well">
        <div class="thread-stuff">
          <div class="thread-title">
            <% if thread.link.nil? || thread.link.length == 0 %>
              <%= link_to thread.title, board_thread_path(thread) %>
            <% else %>
              <%= link_to thread.title, thread.link %>
            <% end %>
          </div>
          <div class="thread-date">Posted: <%= thread.created_at %></div>
          <div class="thread-comment-info">
            <div class="comments">
              <% comments = thread.thread_comments.take 3 %>
              <% comments.each do |comment| %>
                <article class="sample-comment">
                  <div class="comment-content">
                    <%= comment.content %>
                  </div>
                  <div class="comment-info">
                    By
                    <span class="commenter">
                      <%= comment.user.name %>
                    </span>
                    at
                    <span class="created_at">
                      <%= comment.created_at %>
                    </span>
                  </div>
                </article>
              <% end %>
            </div>
          </div>
          <span class="comment-number"><%= thread.thread_comments.size %> comments</span> |
          <%= link_to 'Read more?', thread %>
        </div>
      </div>
    <% end %>
    <%= will_paginate @board_threads %>
  </section>
  <section class="nav side-bar span3">
    <%= render "shared/board_info_panel" %>
    <%= render "shared/new_post_panel" %>
    <%= render "shared/signin_panel" %>
    <%= render "shared/administration_panel" %>
  </section>
</div>