fforum/config/routes.rb
Fforum::Application.routes.draw do
  resources :user_levels

  resources :boards do
    resources :board_threads, only: [:index, :new, :create]
    resources :user_board_permissions, only: [:index, :new, :create]
  end
  match '/boards/:id/marked/threads', to: 'boards#marked_threads', via: 'get',
    as: 'board_marked_threads'
  match '/boards/:id/marked/comments', to: 'boards#marked_comments', via: 'get',
    as: 'board_marked_comments'

  resources :board_threads, only: [:show, :edit, :update, :destroy] do
    resources :thread_comments, only: [:index, :new, :create]
  end
  match '/board_threads/:id/report', to: 'board_threads#report', via: 'get',
    as: 'report_board_thread'
  match '/board_threads/:id/mark', to: 'board_threads#mark', via: 'get',
    as: 'mark_board_thread'
  match '/board_threads/:id/add_review', to: 'board_threads#add_review', via: 'get',
    as: 'add_review_board_thread'

  resources :thread_comments, only: [:show, :edit, :update, :destroy]
  match 'thread_comments/:id/report', to: 'thread_comments#report', via: 'get',
    as: 'report_thread_comment'
  match 'thread_comments/:id/mark', to: 'thread_comments#mark', via: 'get',
    as: 'mark_thread_comment'
  match 'thread_comments/:id/add_review', to: 'thread_comments#add_review', via: 'get',
    as: 'add_review_thread_comment'
  
  resources :user_board_permissions, only: [:show, :edit, :update, :destroy]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via:'get'

  root to: 'boards#index'

  

end

fforum/app/models/board_thread.rb
require 'uri'

class BoardThread < ActiveRecord::Base
  belongs_to :board
  belongs_to :user
  has_many :thread_comments, dependent: :destroy

  validates :title, presence: true
  validates :title, length: { in: 1..80 }
  validates :user_id, presence: true
  validates :board_id, presence: true
  validate :validate_user_id, :validate_board_id, :validate_link_formatted_or_nil

  self.per_page = 10

  private

    def validate_user_id
      unless User.exists?(self.user_id)
        errors.add :user_id, 'does not exist'
      end
    end

    def validate_board_id
      unless Board.exists?(self.board_id)
        errors.add :board_id, 'does not exist'
      end
    end

    def validate_link_formatted_or_nil
      unless self.link.nil?
        unless /\A\z/.match self.link
          errors.add :link, 'invalid URL' unless URI::regexp(%w(http https)).match self.link
        end
      end
    end
end

fforum/app/controllers/board_threads_controller.rb
class BoardThreadsController < ApplicationController
  before_action :set_board_thread, only: [:show, :edit, :update, :destroy, :report, :mark]

  # GET /board_threads
  # GET /board_threads.json
  def index
    if BoardThreadPolicy.index?(current_user)
      @board_threads = BoardThread.all
    else
      redirect_to(root_path)
    end
  end

  # GET /board_threads/1
  def show
    # redirect to root if user has no permission
    redirect_to(root_path) unless BoardThreadPolicy.show?(current_user, @board_thread)
    @thread_comments = @board_thread.thread_comments.paginate(page: params[:page])
  end

  # GET /board_threads/new
  def new
    @board = Board.find(params[:board_id])
    if BoardThreadPolicy.new?(current_user, @board)
      @board_thread = @board.board_threads.build
      @form_submit_url = board_board_threads_path
    else
      redirect_to(root_path)
    end
  end

  # GET /board_threads/1/edit
  def edit
    redirect_to(root_path) unless BoardThreadPolicy.edit?(current_user, @board_thread)
    @form_submit_url = nil
  end

  # POST /board_threads
  def create
    @board = Board.find(params[:board_id])
    if BoardThreadPolicy.create?(current_user, @board)
      @board_thread = BoardThread.new(board_thread_params)
      @board_thread.user = current_user
      @board_thread.board = @board

      if @board_thread.save
        comment = ThreadComment.new
        comment.content = params[:board_thread][:thread_comment][:content]
        comment.user = @board_thread.user
        comment.board_thread = @board_thread

        if comment.save
          redirect_to @board_thread, notice: 'Board thread was successfully created.'
        else
          @board_thread.destroy
          render action: 'new'
        end
      else
        render action: 'new'
      end
    else
      redirect_to(root_path)
    end
  end

  # PATCH/PUT /board_threads/1
  # PATCH/PUT /board_threads/1.json
  def update
    if BoardThreadPolicy.update?(current_user, @board_thread)
      respond_to do |format|
        if @board_thread.update(board_thread_params)
          format.html { redirect_to @board_thread, notice: 'Thread was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @board_thread.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to(root_path)
    end
  end

  # DELETE /board_threads/1
  # DELETE /board_threads/1.json
  def destroy
    if BoardThreadPolicy.destroy?(current_user, @board_thread)
      @board_thread.destroy
      respond_to do |format|
        format.html { redirect_to board_threads_url }
        format.json { head :no_content }
      end
    else
      redirect_to(root_path)
    end
  end

  # Allow a user to confirm they want to report a thread.
  def report
    redirect_to(root_path) unless BoardThreadPolicy.report?(current_user, @board_thread)
  end

  # Mark a thread for moderator review.
  def mark
    if BoardThreadPolicy.mark?(current_user, @board_thread)
      # Some threads might have null values for reported_number.
      if @board_thread.reported_number
        @board_thread.reported_number += 1
      else
        @board_thread.reported_number = 1
      end

      if @board_thread.save
        redirect_to @board_thread, notice: 'Thread was successfully marked for review.'
      else
        redirect_to report_board_thread_path(@board_thread), notice: 'Thread not marked for review.'
      end
    else
      redirect_to(root_path)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_thread
      @board_thread = BoardThread.find(params[:id])
      @board = @board_thread.board
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_thread_params
      params.require(:board_thread).permit(:title, :link, :thread_comment)
    end
end

fforum/app/helpers/board_threads_helper.rb
module BoardThreadsHelper
  def board_thread_page_path(board_thread, page_number)
    board_thread_path(board_thread) + "/p#{page_number}"
  end
end

fforum/app/views/board_threads/_form.html.erb
<%= form_for(@board_thread, url: @form_submit_url) do |f| %>
  <% if @board_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board_thread.errors.count, "error") %> prohibited this board_thread from being saved:</h2>

      <ul>
      <% @board_thread.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :link %>
  </div>

  <% if params[:action] == 'new' %>
    <%= f.fields_for ThreadComment.new do |b| %>
      <div class="field">
        <%= b.label :text %>
        <%= b.text_area :content %>
      </div>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fforum/app/views/board_threads/edit.html.erb
<h1>Editing Thread</h1>

<%= render 'form' %>

<%= link_to 'Back to thread', @board_thread %> |
<% if signed_in? && current_user.at_least_site_or_board_moderator?(@board_thread.board) %>
  <%= link_to 'Back to marked threads list', board_marked_threads_path(@board_thread.board) %>
<% end %>

fforum/app/views/board_threads/index.html.erb
<h1>Listing board_threads</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @board_threads.each do |board_thread| %>
      <tr>
        <td><%= link_to 'Show', board_thread %></td>
        <td><%= link_to 'Edit', edit_board_thread_path(board_thread) %></td>
        <td><%= link_to 'Destroy', board_thread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board thread', new_board_thread_path %>

fforum/app/views/board_threads/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', board_path(@board) %>

fforum/app/views/board_threads/report.html.erb
<p id="notice"><%= notice %></p>
<div class="report-confirmation">
  Are you sure you wish to mark this thread's title and/or link for review by a moderator?
  <br />
  <%= link_to "Yes, mark this thread.", mark_board_thread_path(@board_thread) %>
  <br />
  <%= link_to "No, take me back to the thread.", board_thread_path(@board_thread) %>
</div>

fforum/app/views/board_threads/show.html.erb
<p id="notice"><%= notice %></p>
<% thread = @board_thread %>
<div class="row-fluid">
  <section class="thread-container span9">
    <section class="thread-info well">
      <div class="thread-title">
        <%= link_to thread.title, thread.link %>
      </div>
      <div class="posted-info">
        Posted by 
        <span class="thread-poster">
          <%= thread.user.name %>
        </span>
        at
        <span class="created-at">
          <%= thread.created_at %>
        </span>
        <span class="report-thread">
          | <%= link_to "Report Thread", report_board_thread_path(@board_thread) %> |
        </span>
        <span class="permission-setter-link">
          <% if signed_in? && (current_user.admin? || current_user.at_least_board_moderator?(thread.board)) %>
            <% if thread.user.board_permission(thread.board) %>
              <%= link_to "Manage this user's permissions for this board?", user_board_permission_path(thread.user.board_permission thread.board) %>
            <% else %>
              <%= link_to "Add new permissions for this user on this board?", new_board_user_board_permission_path(thread.board) + "?user_id=#{thread.user.id}" %>
            <% end %>
          <% end %>
        </span>
      </div>
    </section>
    <section class="thread-comments">
      <% comments = @thread_comments %>
      <% comments.each do |comment| %>
        <article class="comment well">
          <div class="comment-content">
            <%= simple_format h(comment.content) %>
          </div>
          <div class="comment-info">
            By
            <span class="commenter">
              <%= comment.user.name %>
            </span>
            at
            <span class="created-at">
              <%= comment.created_at %>
            </span>
            <span class="report-thread">
              | <%= link_to "Report Comment", report_thread_comment_path(comment) %> |
            </span>
            <span class="permission-setter-link">
              <% if signed_in? && (current_user.admin? || current_user.at_least_board_moderator?(thread.board)) %>
                <% if thread.user.board_permission(thread.board) %>
                  <%= link_to "Manage this user's permissions for this board?", user_board_permission_path(thread.user.board_permission thread.board) %>
                <% else %>
                  <%= link_to "Add new permissions for this user on this board?", new_board_user_board_permission_path(thread.board) + "?user_id=#{thread.user.id}" %>
                <% end %>
              <% end %>
            </span>
          </div>
        </article>
      <% end %>
    </section>
    <%= will_paginate @thread_comments %>
  </section>
  <section class="side-bar span3">
    <%= render "shared/board_info_panel" %>
    <%= render "shared/thread_info_panel" %>
    <%= render "shared/signin_panel" %>
  </section>
</div>