fforum/config/routes.rb
Fforum::Application.routes.draw do
  resources :user_levels

  resources :boards do
    resources :board_threads, only: [:index, :new, :create]
    resources :user_board_permissions, only: [:index, :new, :create]
  end
  match '/boards/:id/marked/threads', to: 'boards#marked_threads', via: 'get',
    as: 'board_marked_threads'
  match '/boards/:id/marked/comments', to: 'boards#marked_comments', via: 'get',
    as: 'board_marked_comments'

  resources :board_threads, only: [:show, :edit, :update, :destroy] do
    resources :thread_comments, only: [:index, :new, :create]
  end
  match '/board_threads/:id/report', to: 'board_threads#report', via: 'get',
    as: 'report_board_thread'
  match '/board_threads/:id/mark', to: 'board_threads#mark', via: 'get',
    as: 'mark_board_thread'
  match '/board_threads/:id/add_review', to: 'board_threads#add_review', via: 'get',
    as: 'add_review_board_thread'

  resources :thread_comments, only: [:show, :edit, :update, :destroy]
  match 'thread_comments/:id/report', to: 'thread_comments#report', via: 'get',
    as: 'report_thread_comment'
  match 'thread_comments/:id/mark', to: 'thread_comments#mark', via: 'get',
    as: 'mark_thread_comment'
  match 'thread_comments/:id/add_review', to: 'thread_comments#add_review', via: 'get',
    as: 'add_review_thread_comment'
  
  resources :user_board_permissions, only: [:show, :edit, :update, :destroy]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via:'get'

  root to: 'boards#index'

  

end

fforum/app/views/shared/_administration_panel.html.erb
<% if signed_in? && current_user.at_least_site_or_board_moderator?(@board) %>
  <section class="side-box well">
    <div class="board-marked-threads-link"><%= link_to "Review reported threads", board_marked_threads_path(@board) %></div>
    <div class="board-marked-comments-link"><%= link_to "Review reported comments", board_marked_comments_path(@board) %></div>
  </section>
<% end %>

fforum/app/views/shared/_board_info_panel.html.erb
<section class="side-box well">
  <div class="board-title"><%= link_to @board.title, @board %></div>
  <div class="board-description"><%= @board.description %></div>
  <% if params[:controller] == 'boards' && params[:action] == 'show' %>
    <%= will_paginate @board_threads %>
  <% end %>
</section>

fforum/app/views/shared/_new_board_panel.html.erb
<% if signed_in? %>
  <section class="side-box well">
    <div class="make-new-board">
      Make a <%= link_to 'New Board', new_board_path %>!
    </div>
  </section>
<% end %>

fforum/app/views/shared/_new_post_panel.html.erb
<% if signed_in? %>
  <section class="side-box well">
    <div class="make-new-post">
      Make a <%= link_to 'New Post', new_board_board_thread_path(@board) %>!
    </div>
  </section>
<% end %>

fforum/app/views/shared/_signin_panel.html.erb
<% unless signed_in? %>
  <section class="side-box well">
    <div class="sign-in">
      <%= link_to 'Sign up', signup_path %> or <%= link_to 'Sign in', signin_path %> to start posting!
    </div>
  </section>
<% end %>

fforum/app/views/shared/_site_info_panel.html.erb
<section class="side-box well">
  <% if signed_in? %>
    <div class="site-description-signed-in">
      <p>Blueit is a site for people to exchange links and ideas about whatever topics they want. <%= link_to 'Make a board', new_board_path %> of your own and start sharing today!</p>
    </div>
  <% else %>
    <div class="site-description-signed-out">
      <p>Blueit is a site for people to exchange links and ideas about whatever topics they want. <%= link_to 'Sign up', signup_path %> and start sharing today!</p>
    </div>
  <% end %>
</section>

fforum/app/views/shared/_thread_info_panel.html.erb
<section class="side-box well">
  <div class="board-title">
    <%= link_to @board_thread.title, @board_thread %>
  </div>

  <% if signed_in? %>
  <div class="make-new-comment">
    <%= link_to 'Add Comment', new_board_thread_thread_comment_path(@board_thread) %>!
  </div>
  <% end %>
  
  <%= link_to 'Back to post list', board_path(@board_thread.board) %>
  <%= will_paginate @thread_comments %>
</section>