fforum/config/routes.rb
Fforum::Application.routes.draw do
  resources :user_levels

  resources :boards do
    resources :board_threads, only: [:index, :new, :create]
    resources :user_board_permissions, only: [:index, :new, :create]
  end
  match '/boards/:id/marked/threads', to: 'boards#marked_threads', via: 'get',
    as: 'board_marked_threads'
  match '/boards/:id/marked/comments', to: 'boards#marked_comments', via: 'get',
    as: 'board_marked_comments'

  resources :board_threads, only: [:show, :edit, :update, :destroy] do
    resources :thread_comments, only: [:index, :new, :create]
  end
  match '/board_threads/:id/report', to: 'board_threads#report', via: 'get',
    as: 'report_board_thread'
  match '/board_threads/:id/mark', to: 'board_threads#mark', via: 'get',
    as: 'mark_board_thread'
  match '/board_threads/:id/add_review', to: 'board_threads#add_review', via: 'get',
    as: 'add_review_board_thread'

  resources :thread_comments, only: [:show, :edit, :update, :destroy]
  match 'thread_comments/:id/report', to: 'thread_comments#report', via: 'get',
    as: 'report_thread_comment'
  match 'thread_comments/:id/mark', to: 'thread_comments#mark', via: 'get',
    as: 'mark_thread_comment'
  match 'thread_comments/:id/add_review', to: 'thread_comments#add_review', via: 'get',
    as: 'add_review_thread_comment'
  
  resources :user_board_permissions, only: [:show, :edit, :update, :destroy]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via:'get'

  root to: 'boards#index'

  

end

fforum/app/models/thread_comment.rb
class ThreadComment < ActiveRecord::Base
  belongs_to :board_thread
  belongs_to :user

  validates :content, presence: true
  validates :content, length: { in: 1..1000 }
  validates :user_id, presence: true
  validates :board_thread_id, presence: true
  validate :validate_user_id
  validate :validate_board_thread_id

  self.per_page = 10

  private
  # TODO: refactor this along with similar code in app/models/board_thread.rb
    def validate_user_id
      if !User.exists?(self.user_id)
        errors.add :user_id, 'does not exist'
      end
    end

    def validate_board_thread_id
      if !BoardThread.exists?(self.board_thread_id)
        errors.add :board_thread_id, 'does not exist'
      end
    end
end

fforum/app/controllers/thread_comments_controller.rb
class ThreadCommentsController < ApplicationController
  before_action :set_thread_comment, only: [:show, :edit, :update, :destroy, :report, :mark]

  # GET /thread_comments
  # GET /thread_comments.json
  def index
    if ThreadCommentPolicy.index?(current_user)
      @thread_comments = ThreadComment.all
    else
      redirect_to(root_path)
    end
  end

  # GET /thread_comments/1
  # GET /thread_comments/1.json
  def show
    redirect_to(root_path) unless ThreadCommentPolicy.show?(current_user, @thread_comment)
  end

  # GET /thread_comments/new
  def new
    @board_thread = BoardThread.find(params[:board_thread_id])
    if ThreadCommentPolicy.new?(current_user, @board_thread.board)
      @thread_comment = @board_thread.thread_comments.build
      @form_submit_url = board_thread_thread_comments_path
    else
      redirect_to(root_path)
    end
  end

  # GET /thread_comments/1/edit
  def edit
    redirect_to(root_path) unless ThreadCommentPolicy.edit?(current_user, @thread_comment)
    @form_submit_url = nil
  end

  # POST /thread_comments
  # POST /thread_comments.json
  def create
    @board_thread = BoardThread.find(params[:board_thread_id])
    if ThreadCommentPolicy.create?(current_user, @board_thread.board)
      @thread_comment = ThreadComment.new(thread_comment_params)
      @thread_comment.user = current_user
      @thread_comment.board_thread = @board_thread
      @board_thread = @thread_comment.board_thread

      if @thread_comment.save
        redirect_to @board_thread, notice: 'Comment was successfully created.'
      else
        render action: 'new'
      end
    else
      redirect_to(root_path)
    end
  end

  # PATCH/PUT /thread_comments/1
  # PATCH/PUT /thread_comments/1.json
  def update
    if ThreadCommentPolicy.update?(current_user, @thread_comment)
      respond_to do |format|
        if @thread_comment.update(thread_comment_params)
          format.html { redirect_to @thread_comment.board_thread, notice: 'Thread comment was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @thread_comment.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to(root_path)
    end
  end

  # DELETE /thread_comments/1
  # DELETE /thread_comments/1.json
  def destroy
    if ThreadCommentPolicy.destroy?(current_user, @thread_comment)
      @thread_comment.destroy
      respond_to do |format|
        format.html { redirect_to thread_comments_url }
        format.json { head :no_content }
      end
    else
      redirect_to(root_path)
    end
  end

  # Allow a user to confirm they want to report a comment.
  def report
    redirect_to(root_path) unless ThreadCommentPolicy.report?(current_user, @thread_comment)
  end

  # Mark a comment for moderator review.
  def mark
    if ThreadCommentPolicy.mark?(current_user, @thread_comment)
      # Some comments might have null values for reported_number.
      if @thread_comment.reported_number
        @thread_comment.reported_number += 1
      else
        @thread_comment.reported_number = 1
      end

      if @thread_comment.save
        redirect_to @thread_comment.board_thread, notice: 'Comment was successfully marked for review.'
      else
        redirect_to report_thread_comment_path(@thread_comment), notice: 'Comment not marked for review.'
      end
    else
      redirect_to(root_path)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thread_comment
      @thread_comment = ThreadComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thread_comment_params
      params.require(:thread_comment).permit(:content)
    end
end

fforum/app/helpers/thread_comments_helper.rb
module ThreadCommentsHelper
end

fforum/app/views/thread_comments/_form.html.erb
<%= form_for(@thread_comment, url: @form_submit_url) do |f| %>
  <% if @thread_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thread_comment.errors.count, "error") %> prohibited this thread_comment from being saved:</h2>

      <ul>
      <% @thread_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Comment_here %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fforum/app/views/thread_comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Back to thread', @thread_comment.board_thread %> |
<% if signed_in? && (current_user.at_least_site_or_board_moderator?(@thread_comment.board_thread.board)) %>
  <%= link_to 'Back to marked comments list', board_marked_comments_path(@thread_comment.board_thread.board) %>
<% end %>

fforum/app/views/thread_comments/index.html.erb
<h1>Listing thread_comments</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @thread_comments.each do |thread_comment| %>
      <tr>
        <td><%= link_to 'Show', thread_comment %></td>
        <td><%= link_to 'Edit', edit_thread_comment_path(thread_comment) %></td>
        <td><%= link_to 'Destroy', thread_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thread comment', new_thread_comment_path %>

fforum/app/views/thread_comments/new.html.erb
<h1>New Thread Comment</h1>

<%= render 'form' %>

<%= link_to 'Back to thread', board_thread_path(@thread_comment.board_thread.id) %>

fforum/app/views/thread_comments/report.html.erb
<p id="notice"><%= notice %></p>
<div class="report-confirmation">
  Are you sure you wish to mark this comment for review by a moderator?
  <br />
  <%= link_to "Yes, mark this comment.", mark_thread_comment_path(@thread_comment) %>
  <br />
  <%= link_to "No, take me back to the thread.", board_thread_path(@thread_comment.board_thread) %>
</div>

fforum/app/views/thread_comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_thread_comment_path(@thread_comment) %> |
<%= link_to 'Back', thread_comments_path %>